export const LIST_TODOS = 'LIST_TODOS';
export const LIST_TODOS_SUCCESS = 'LIST_TODOS_SUCCESS';
export const LIST_TODOS_FAILURE = 'LIST_TODOS_FAILURE';

export const CREATE_TODO = 'CREATE_TODO';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const CREATE_TODO_FAILURE = 'CREATE_TODO_FAILURE';

export const READ_TODO = 'READ_TODO';
export const READ_TODO_SUCCESS = 'READ_TODO_SUCCESS';
export const READ_TODO_FAILURE = 'READ_TODO_FAILURE';

export const UPDATE_TODO = 'UPDATE_TODO';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_FAILURE = 'UPDATE_TODO_FAILURE';

export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE';
