export const ADD_TODO = 'ADD_TODO'
export const TOGGLE_STATUS_TODO = 'TOGGLE_STATUS_TODO'
export const SHOW_VISIBLE = 'SHOW_VISIBLE'

export const LIST_TODOS = 'LIST_TODOS'
export const LIST_TODOS_SUCCESS = 'LIST_TODOS_SUCCESS'
export const LIST_TODOS_FAILURE = 'LIST_TODOS_FAILURE'

export const CREATE_TODO = 'CREATE_TODO'
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS'
export const CREATE_TODO_FAILURE = 'CREATE_TODO_FAILURE'
